Fixed whitespace in github actions yaml

diff --git a/.github/workflows/version-check.yml b/.github/workflows/version-check.yml
--- a/.github/workflows/version-check.yml
+++ b/.github/workflows/version-check.yml
@@ -2,7 +2,7 @@ name: Check for Updates
 
 on:
   schedule:
-  - cron: "28 */6 * * *"
+    - cron: "28 */6 * * *"
   workflow_dispatch:
 
 env:
@@ -13,47 +13,46 @@ jobs:
     name: Compare Local and Remote Versions
     runs-on: ubuntu-latest
     outputs:
-        update_required: ${{ steps.compare_versions.outputs.update_required }}
-        current_version: ${{ steps.get_release_version.outputs.current_version }}
-        remote_version: ${{ steps.get_remote_version.outputs.remote_version }}
+      update_required: ${{ steps.compare_versions.outputs.update_required }}
+      current_version: ${{ steps.get_release_version.outputs.current_version }}
+      remote_version: ${{ steps.get_remote_version.outputs.remote_version }}
 
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v4
+      - name: Checkout repository
+        uses: actions/checkout@v4
 
-    - name: Get remote version
-      id: get_remote_version
-      run: |
-        set -e
-        echo "Getting version from $VERSION_CHECK_URL"
-        REMOTE_VERSION=$(curl -s $VERSION_CHECK_URL | head -n 1)
-        echo "Remote version: $REMOTE_VERSION" >> $GITHUB_STEP_SUMMARY
-        echo "remote_version=$REMOTE_VERSION" >> "$GITHUB_OUTPUT"
+      - name: Get remote version
+        id: get_remote_version
+        run: |
+          set -e
+          echo "Getting version from $VERSION_CHECK_URL"
+          REMOTE_VERSION=$(curl -s $VERSION_CHECK_URL | head -n 1)
+          echo "Remote version: $REMOTE_VERSION" >> $GITHUB_STEP_SUMMARY
+          echo "remote_version=$REMOTE_VERSION" >> "$GITHUB_OUTPUT"
 
-    - name: Compare versions
-      id: compare_versions
-      env:
-        CURRENT_VERSION : ${{ steps.get_release_version.outputs.current_version }}
-        REMOTE_VERSION : ${{ steps.get_remote_version.outputs.remote_version }}
-      run: |
-        set -e
-        CURRENT_VERSION="$(git tag --list | grep -e '^v[0-9]+\.[0-9]+' | sort -V | tail -n 1)"
-        echo "Current version: $CURRENT_VERSION" >> $GITHUB_STEP_SUMMARY
-        echo "current_version=$CURRENT_VERSION" >> "$GITHUB_OUTPUT"
-        if [ "$(printf '%s\n' "$CURRENT_VERSION" "$REMOTE_VERSION" | sort -V | tail -n 1)" == "$CURRENT_VERSION" ]; then
-            echo "Current version $CURRENT_VERSION is greater than or equal to Remote version $REMOTE_VERSION."
-            echo "No update required." >> $GITHUB_STEP_SUMMARY
-            echo "update_required=false" >> "$GITHUB_OUTPUT"
-        else
-            echo "Remote version $REMOTE_VERSION is newer than Current version $CURRENT_VERSION."
-            echo "Creating release... :rocket:" >> $GITHUB_STEP_SUMMARY
-            echo "update_required=true" >> "$GITHUB_OUTPUT"
-        fi
+      - name: Compare versions
+        id: compare_versions
+        env:
+          CURRENT_VERSION : ${{ steps.get_release_version.outputs.current_version }}
+          REMOTE_VERSION : ${{ steps.get_remote_version.outputs.remote_version }}
+        run: |
+          set -e
+          CURRENT_VERSION="$(git tag --list | grep -e '^v[0-9]+\.[0-9]+' | sort -V | tail -n 1)"
+          echo "Current version: $CURRENT_VERSION" >> $GITHUB_STEP_SUMMARY
+          echo "current_version=$CURRENT_VERSION" >> "$GITHUB_OUTPUT"
+          if [ "$(printf '%s\n' "$CURRENT_VERSION" "$REMOTE_VERSION" | sort -V | tail -n 1)" == "$CURRENT_VERSION" ]; then
+              echo "Current version $CURRENT_VERSION is greater than or equal to Remote version $REMOTE_VERSION."
+              echo "No update required." >> $GITHUB_STEP_SUMMARY
+              echo "update_required=false" >> "$GITHUB_OUTPUT"
+          else
+              echo "Remote version $REMOTE_VERSION is newer than Current version $CURRENT_VERSION."
+              echo "Creating release... :rocket:" >> $GITHUB_STEP_SUMMARY
+              echo "update_required=true" >> "$GITHUB_OUTPUT"
+          fi
 
       - name: Clear Cached HamClock
         if: needs.version-check.outputs.update_required == 'true'
-        run: |
-          gh cache delete hamclock
+        run: gh cache delete hamclock
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           GH_REPO: ${{ github.repository }}
